"""empty message

Revision ID: 5a3dd9b87c99
Revises: 
Create Date: 2022-07-27 14:22:16.029077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3dd9b87c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'guest_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['state_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lga', type_='foreignkey')
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('guests', 'guest_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
